---
- name: Deploy Management Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config/infra/vsphere.yml
    - ../config/infra/passwords.yml
  tasks:
  - name: Deploy Management - Include Management Tasks
    include_tasks: 
      file: "infra/{{ item }}.yml"
      apply:
        tags:
          - deploy
          - "{{ item }}"
    with_items:
      - management
    tags:
      - always

- name: Deploy Management - Configure Gateway
  hosts: management-gateway
  become: yes
  gather_facts: no
  tasks:
  - name: Deploy Management - Configure Gateway
    include_tasks:
      file: infra/management/01-gateway.yml
      apply:
        tags:
          - deploy
          - management
          - awx
    tags:
      - always

- name: Deploy Management - Install and Configure AWX
  hosts: management-awx
  vars_files:
    - ../config/infra/passwords.yml
  become: yes
  gather_facts: no
  tasks:
  - name: Deploy Management - Install and Configure AWX
    include_tasks:
      file: infra/management/{{ item }}.yml
      apply:
        tags:
          - deploy
          - management
          - awx
    with_items:
      - 02-install_deps_awx
      - 03-install_awx
    tags:
      - always

- name: Deploy Management - Initialize AWX
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ../config/infra/vsphere.yml
    - ../config/infra/passwords.yml
    - ../config/awx.yml
  tasks:
  - name: Deploy Management - Clean and Initialize AWX
    include_tasks:
      file: infra/management/{{ item }}.yml
      apply:
        tags:
          - deploy
          - management
          - awx
          - init-awx
    with_items:
      - 04-clean_awx
      - 05-init_awx
      - 06-init_awx_tmpl
      - 07-custom_awx
      - 08-custom_awx_tmpl
    tags:
      - always
